---
- hosts: all
  pre_tasks:
    - name: install packages for testing under docker
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - selinux-policy
        - libselinux-python
        - openssh-server
        - which
  vars:
    #Travis doens't like modprobe
    rhel7cis_firewall: iptables
    rhel7cis_rule_1_1_1_1: false
    rhel7cis_rule_3_6_1: false
    rhel7cis_rule_3_6_2: false
    rhel7cis_rule_3_6_3: false
    rhel7cis_rule_3_6_4: false
    rhel7cis_rule_3_6_5: false
    rhel7cis_rule_1_1_1_2: false
    rhel7cis_rule_1_1_1_3: false
    rhel7cis_rule_1_1_1_4: false
    rhel7cis_rule_1_1_1_5: false
    rhel7cis_rule_1_1_1_6: false
    rhel7cis_rule_1_1_1_7: false
    rhel7cis_rule_1_1_1_8: false
  roles:
    - role: RHEL7-CIS
